apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: false
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
      manageAlerts: true
      alertmanagerUid: alertmanager

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    isDefault: false
    version: 1
    editable: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: "trace_id"
          matcherRegex: "traceID=(.+)"
          url: "${__value.raw}"

  - name: Node Metrics
    type: prometheus
    access: proxy
    orgId: 1
    url: http://node-exporter:9100
    isDefault: false
    version: 1
    editable: false
    jsonData:
      timeInterval: 15s

  - name: Container Metrics
    type: prometheus
    access: proxy
    orgId: 1
    url: http://cadvisor:8080
    isDefault: false
    version: 1
    editable: false
    jsonData:
      timeInterval: 15s

  - name: OpenEdX Metrics
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090/federate
    isDefault: false
    version: 1
    editable: false
    jsonData:
      timeInterval: 15s
      httpMethod: GET
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo

secureJsonData:
  httpHeaderValue1: ''

deleteDatasources:
  - name: Graphite
    orgId: 1

