global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'openedx-lms'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['lms:8000']

  - job_name: 'openedx-cms'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cms:8000']

