# CMS Configuration for Open edX
---
PLATFORM_NAME: "${PLATFORM_NAME}"
SITE_NAME: "${CMS_BASE}"
LMS_BASE: "${LMS_BASE}"
CMS_BASE: "${CMS_BASE}"
LMS_ROOT_URL: "https://${LMS_BASE}"
CMS_ROOT_URL: "https://${CMS_BASE}"

FEATURES:
  ENABLE_DISCUSSION_SERVICE: true
  ENABLE_COURSEWARE_SEARCH: true
  ENABLE_COURSE_DISCOVERY: true
  ENABLE_DASHBOARD_SEARCH: true
  ENABLE_COMBINED_LOGIN_REGISTRATION: true
  PREVIEW_LMS_BASE: "${LMS_BASE}"
  ENABLE_COUCHDB: true

# Email Settings
EMAIL_BACKEND: 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST: 'smtp.example.com'
EMAIL_PORT: 587
EMAIL_USE_TLS: true
EMAIL_HOST_USER: 'your-email@example.com'
EMAIL_HOST_PASSWORD: 'your-email-password'
DEFAULT_FROM_EMAIL: "${CONTACT_EMAIL}"

# CouchDB Storage
COUCHDB_HOST: 'couchdb'
COUCHDB_PORT: 5984
COUCHDB_USER: "${COUCHDB_USER}"
COUCHDB_PASSWORD: "${COUCHDB_PASSWORD}"
COUCHDB_DB_NAME: "openedx_${VM_INDEX}"

# Storage Configuration
DEFAULT_FILE_STORAGE: 'storage.couchdb_storage.CouchDBStorage'
COURSE_IMPORT_EXPORT_STORAGE: 'storage.couchdb_storage.CouchDBStorage'
VIDEO_TRANSCRIPTS_STORAGE: 'storage.couchdb_storage.CouchDBStorage'
GRADES_DOWNLOAD_STORAGE: 'storage.couchdb_storage.CouchDBStorage'

