#cloud-config
package_update: true
package_upgrade: true

packages:
  - docker.io=20.10.12-0ubuntu2~20.04.1
  - docker-compose=1.29.2-1
  - curl=7.68.0-1ubuntu2.15
  - jq=1.6-1ubuntu0.20.04.1
  - git=1:2.25.1-1ubuntu3.10
  - rsync=3.1.3-8ubuntu0.3
  - ufw=0.36-6ubuntu1

groups:
  - docker

users:
  - name: openedx
    groups: docker
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ${file(ssh_public_key_path)}

  - name: backup-user
    shell: /bin/bash
    sudo: false
    ssh_authorized_keys:
      - ${file(ssh_public_key_path)}

write_files:
  - path: /home/openedx/backup_info.env
    permissions: '0644'
    content: |
      COUCHDB_USER=${couchdb_user}
      COUCHDB_PASSWORD=${couchdb_password}
      PRODUCTION_NODE_IPS=${join(",", production_node_ips)}

runcmd:
  # Install specific package versions with fallback
  - |
    if ! apt-get install -y docker.io=20.10.12-0ubuntu2~20.04.1; then
      echo "Specific docker version not found, installing latest..."
      apt-get install -y docker.io
    fi
  - |
    if ! apt-get install -y docker-compose=1.29.2-1; then
      echo "Specific docker-compose version not found, installing latest..."
      apt-get install -y docker-compose
    fi
  - |
    if ! apt-get install -y rsync=3.1.3-8ubuntu0.3; then
      echo "Specific rsync version not found, installing latest..."
      apt-get install -y rsync
    fi
  # Configure firewall
  - ufw allow 22/tcp
  - ufw --force enable

  # Create backup directories
  - mkdir -p /backup/daily /backup/weekly /backup/monthly
  - chown -R backup-user:backup-user /backup

  # Clone repository
  - su - openedx -c "git clone https://github.com/yourusername/openedx-ha.git /home/openedx/openedx-ha"

  # Configure environment
  - su - openedx -c "cd /home/openedx/openedx-ha && cp .env.example .env"
  - su - openedx -c "cd /home/openedx/openedx-ha && sed -i 's/COUCHDB_USER=admin/COUCHDB_USER=${couchdb_user}/' .env"
  - su - openedx -c "cd /home/openedx/openedx-ha && sed -i 's/COUCHDB_PASSWORD=password/COUCHDB_PASSWORD=${couchdb_password}/' .env"

  # Setup backup cron jobs
  - su - openedx -c "(crontab -l 2>/dev/null; echo '0 1 * * * cd /home/openedx/openedx-ha && ./scripts/backup-daily.sh >> /home/openedx/backup.log 2>&1') | crontab -"
  - su - openedx -c "(crontab -l 2>/dev/null; echo '0 2 * * 0 cd /home/openedx/openedx-ha && ./scripts/backup-weekly.sh >> /home/openedx/backup.log 2>&1') | crontab -"
  - su - openedx -c "(crontab -l 2>/dev/null; echo '0 3 1 * * cd /home/openedx/openedx-ha && ./scripts/backup-monthly.sh >> /home/openedx/backup.log 2>&1') | crontab -"


