#cloud-config
package_update: true
package_upgrade: true

packages:
  - docker.io=20.10.12-0ubuntu2~20.04.1
  - docker-compose=1.29.2-1
  - curl=7.68.0-1ubuntu2.15
  - jq=1.6-1ubuntu0.20.04.1
  - git=1:2.25.1-1ubuntu3.10
  - rsync=3.1.3-8ubuntu0.3
  - ufw=0.36-6ubuntu1

groups:
  - docker

users:
  - name: openedx
    groups: docker
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ${file(ssh_public_key_path)}

write_files:
  - path: /home/openedx/vm_info.env
    permissions: '0644'
    content: |
      VM_INDEX=${vm_index}
      COUCHDB_USER=${couchdb_user}
      COUCHDB_PASSWORD=${couchdb_password}
      INTERNAL_IP=10.0.1.${vm_index + 9}
      OTHER_NODE_IPS=${join(",", other_node_ips)}
      DOMAIN_NAME=${domain_name}

runcmd:
  # Configure firewall
  - ufw allow 22/tcp
  - ufw allow 80/tcp
  - ufw allow 443/tcp
  - ufw allow from 10.0.0.0/16 to any port 5984 proto tcp
  - ufw --force enable

  # Fix Docker permissions
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker openedx

  # Clone repository
  - su - openedx -c "git clone https://github.com/yourusername/openedx-ha.git /home/openedx/openedx-ha"

  # Configure environment
  - su - openedx -c "cd /home/openedx/openedx-ha && cp docker/.env.example docker/.env"
  - su - openedx -c "cd /home/openedx/openedx-ha && sed -i 's/COUCHDB_USER=admin/COUCHDB_USER=${couchdb_user}/' docker/.env"
  - su - openedx -c "cd /home/openedx/openedx-ha && sed -i 's/COUCHDB_PASSWORD=password/COUCHDB_PASSWORD=${couchdb_password}/' docker/.env"
  - su - openedx -c "cd /home/openedx/openedx-ha && sed -i 's/VM_INDEX=1/VM_INDEX=${vm_index}/' docker/.env"

  # Start containers
  - su - openedx -c "cd /home/openedx/openedx-ha/docker && docker-compose up -d"

  # Setup health check cron job
  - su - openedx -c "(crontab -l 2>/dev/null; echo '*/5 * * * * cd /home/openedx/openedx-ha/scripts && ./health-check.sh >> /home/openedx/health-check.log 2>&1') | crontab -"

  # Create Caddy directories
  - mkdir -p /home/openedx/openedx-ha/docker/config/caddy/data
  - mkdir -p /home/openedx/openedx-ha/docker/config/caddy/config
  - chown -R openedx:openedx /home/openedx/openedx-ha/docker/config/caddy

  # Allow monitoring ports for internal network only
  - ufw allow from 10.0.0.0/16 to any port 9090 proto tcp  # Prometheus
  - ufw allow from 10.0.0.0/16 to any port 9100 proto tcp  # Node Exporter
  - ufw allow from 10.0.0.0/16 to any port 8080 proto tcp  # cAdvisor
  - ufw allow from 10.0.0.0/16 to any port 3000 proto tcp  # Grafana